import '../globals.css'
import { Header, Footer } from '@/components/Layout'
import VerticalMarquees from '@/components/Layout/home/marquee'
import 'react-toastify/dist/ReactToastify.css'
export const metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
}

export default function ContentRootLayout({ children }) {
  return (
    <>
      <Header />
      {children}

      <Footer />
    </>
  )
}
